config/routes.rb
Rails.application.routes.draw do


  root  'books#index'
  get   '/editbook'    ,to: 'books#edit'   
  get   '/newbook'     ,to: 'books#new'
  get   'books'        ,to: 'books#show'
  get   '/signup'      ,to: 'users#new'
  post  '/signup'      ,to: 'users#create'
  get   '/login'       ,to: 'sessions#new'
  post  '/login'       ,to: 'sessions#create'
  delete'/logout'      ,to: 'sessions#destroy'
  get   '/edit'        ,to: 'users#edit'
  get   '/index'       ,to: 'users#index'
  post  '/authors'     ,to: 'authors#create'
  get   '/authors'     ,to: 'authors#new'
  get   '/allauthors'  ,to: 'authors#index'
  get   '/newcategory' ,to: 'categories#new'
  get   '/newpublisher',to: 'publishers#new'


  get   'categories/show'
  
  resources :publishers
  resources :authors
  resources :categories
  resources :users
  resources :books do
    resources :reviews
  end
  
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category
	belongs_to :author
	belongs_to :publisher
	has_many :reviews, dependent: :destroy
	validates :name, presence: true
	validates :book_image, presence: true
    has_attached_file :book_image, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_image, content_type: /\Aimage\/.*\z/ 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def new
  	@book = Book.new
    @categories = Category.all.map{ |c| [c.types,c.id] }
    @authors = Author.all.map{ |c| [c.author,c.id] }
    @publishers = Publisher.all.map{ |c| [c.name,c.id] }
  end

  def create
  	@book = Book.new(book_params)
    @book.category_id = params[:category_id]
    @book.author_id = params[:author_id]
    @book.publisher_id = params[:publisher_id]
  	if @book.save
  		redirect_to root_path
    else
    	render 'new'
    end
  end

  def index
    if params[:category].blank?
  	  @book = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(types: params[:category]).id
      @book = Book.where(:category_id => @category_id).order("created_at DESC")
    end
    @book = Book.where("name LIKE ?","%#{params[:search]}%")
  end

  def show
    if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rate).round(2)
    end
  end

  def review
    @review = @book.reviews.build if logged_in?
  end
  
  def edit
    @categories = Category.all.map{ |c| [c.types,c.id] }
    @authors = Author.all.map{ |c| [c.author,c.id] }
    @publishers = Publisher.all.map{ |c| [c.name,c.id] }

  end

  def update
    @book.category_id = params[:category_id]
    @book.author_id = params[:author_id]
    @book.publisher_id = params[:publisher_id]
    if @book.update(book_params)
      flash[:success] = "Book updated"
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
  	@book.destroy
  	redirect_to root_path
  end

  private
    def book_params
    	params.require(:book).permit(:name,:book_image,:description,:year,:category_id,
                                                             :author_id,:publisher_id)
    end

    def find_book
    	@book = Book.find(params[:id])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: {multipart: true} do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'shared/book_error_messages' %>
        
        <hh1><strong>Category</strong></hh1>
        <div class="field">
          <%= link_to 'New category ?', '/newcategory' %>
        </div>
        <%= select_tag(:category_id, options_from_collection_for_select(Category.all, :id, :types)) %>

        <hh1><strong>Publisher</strong></hh1> 
        <div class="field">
          <%= link_to 'New publisher ?', '/newpublisher' %>
        </div>
        <%= select_tag(:publisher_id, options_from_collection_for_select(Publisher.all, :id, :name)) %>

        <hh1><strong>Author</strong></hh1>
        <div class="field">
          <%= link_to 'New author ?', authors_path %>
        </div>
        <%= select_tag(:author_id, options_from_collection_for_select(Author.all, :id, :author)) %>

        <div class="field">
          <%= f.label :image %>
          <%= f.file_field :book_image, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :year %>
          <%= f.text_field :year, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit "save", class: "btn btn-primary" %>
        </div> 

    </div>
  </div>
<% end %>

app/views/books/edit.html.erb
<% provide(:title, 'Edit book') %>
<h1>Edit Book</h1>
<%= render 'form', book: @book %>

app/views/books/index.html.erb
<% provide(:title, 'All book') %>

<div class="row">
<%= form_tag root_path, :method => 'get' do %>
<div class="col-md-5 col-md-offset-3">
   <hh1><strong>Search by book's name</strong></hh1>
   <%= text_field_tag :search, params[:search], class: 'form-control' %>
</div>
<div class="col-md-2 col-md-offset-0">
   <br>
   <%= submit_tag "Search", class: "btn-custom" %>
</div>
<% end %>
</div>

<h1 class="current-category"><%= params[:category] %></h1>
<% if @book.count == 0 %>
   <h1>There are no book match your order</h1>
<% else %> 
   <div class="row">
      <% @book.each do |book| %>
         <div class="col-md-3">
            <a href="/books/<%= book.id %>">
        	   <%= image_tag book.book_image.url(:book_index), class: "book" %>
            </a>
         </div>
      <% end %>   
   </div>   
<% end %> 

app/views/books/new.html.erb
<% provide(:title, "Add book") %>
<h1>New Book</h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<% provide(:title, @book.name) %>

 <div class="row">  
  <div class="col-md-4">
    <div class="row">

      <%= image_tag @book.book_image.url(:book_show), class: "book_show" %>
      <div class="reviews">
         <hh>Reviews</hh>
            <%= render @book.reviews %>      
      </div>
      <% if logged_in? %>
        <div>
          <%= link_to "Add review", new_book_review_path(@book), class: "btn btn-custom2" %><br>
        </div>
      <% end %>
    </div>
  </div>
   

   
   <div class="col-md-8" >
      <div class="book-info" >
          <hh class="book-title"><%= @book.name %></hh><br>
          <hh2 class="book-year"><span>Publish year : </span><strong><%= @book.year %></hh2></strong><br>
          <hh3>category:<strong> <%= @book.category.types %></strong></hh3><br>
          <hh3>publisher:<strong> <%= @book.publisher.name %></strong></hh3><br>
          <h3 class="book-author"><span>From: </span><%= @book.author.author %></h3>
          <hh4 class="avg-rating">Average Rating</hh4>
          <div class="average-review-rate" data-score=<%= @average_review %>></div>
          <span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews </span>
          <p class="book-desc"><%= @book.description %></p>
      </div>

      <div class="links btn-group">
        <%= link_to "Back", root_path, class: "btn btn-custom" %>
        <% if logged_in? %>
          <% if current_user.admin %>
            <%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
            <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "You really want 
                                                   to delete this review" }, class: "btn btn-custom" %>
          <% end %>
        <% end %>
      </div>

   </div>
</div>



<script>
  $('.review-rate').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rate').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>