config/routes.rb
Rails.application.routes.draw do


  root  'books#index'
  get   '/editbook'    ,to: 'books#edit'   
  get   '/newbook'     ,to: 'books#new'
  get   'books'        ,to: 'books#show'
  get   '/signup'      ,to: 'users#new'
  post  '/signup'      ,to: 'users#create'
  get   '/login'       ,to: 'sessions#new'
  post  '/login'       ,to: 'sessions#create'
  delete'/logout'      ,to: 'sessions#destroy'
  get   '/edit'        ,to: 'users#edit'
  get   '/index'       ,to: 'users#index'
  post  '/authors'     ,to: 'authors#create'
  get   '/authors'     ,to: 'authors#new'
  get   '/allauthors'  ,to: 'authors#index'
  get   '/newcategory' ,to: 'categories#new'
  get   '/newpublisher',to: 'publishers#new'


  get   'categories/show'
  
  resources :publishers
  resources :authors
  resources :categories
  resources :users
  resources :books do
    resources :reviews
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id
    if @review.save
      flash[:success] = "Review created!"
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update  
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

    def review_params
      params.require(:review).permit(:comment,:rate)
    end

    def find_book
      @book = Book.find(params[:book_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>

    <% if @review.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          <%= pluralize(@review.errors.count, "error") %>.
        </div>
      
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

	<div id="rating-form">
		<label>Rating score</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rate]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
   <div class="review-rate" data-score="<%= review.rate %>"></div>
   <p class="review-comment"><%= review.comment %><br></p>

   <% if logged_in? %>
      <% if review.user_id == current_user.id || current_user.admin %>
	     <div class="links btn-group">
		    <%= link_to "Edit",edit_book_review_path(review.book, review), class: "btn btn-custom" %>
		    <%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: 
	   	                                  { confirm: "Are you sure?" }, class: "btn btn-custom" %>
	     </div>
      <% end %>
   <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-book-form">

		<h1>Edit Review</h1>

        <% if @review.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-danger">
              <%= pluralize(@review.errors.count, "error") %>.
            </div>
      
            <ul>
              <% @review.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>    

		<%= simple_form_for([@book, @review]) do |f| %>
		    <div id="rating-form">
		        <label>Rating score</label>
		    </div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom" %>
		<% end %>
	</div>
</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rate]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>New Review</h1>

    <%= render 'form',book: @book%>
</div>