config/routes.rb
Rails.application.routes.draw do


  root  'books#index'
  get   '/editbook'    ,to: 'books#edit'   
  get   '/newbook'     ,to: 'books#new'
  get   'books'        ,to: 'books#show'
  get   '/signup'      ,to: 'users#new'
  post  '/signup'      ,to: 'users#create'
  get   '/login'       ,to: 'sessions#new'
  post  '/login'       ,to: 'sessions#create'
  delete'/logout'      ,to: 'sessions#destroy'
  get   '/edit'        ,to: 'users#edit'
  get   '/index'       ,to: 'users#index'
  post  '/authors'     ,to: 'authors#create'
  get   '/authors'     ,to: 'authors#new'
  get   '/allauthors'  ,to: 'authors#index'
  get   '/newcategory' ,to: 'categories#new'
  get   '/newpublisher',to: 'publishers#new'


  get   'categories/show'
  
  resources :publishers
  resources :authors
  resources :categories
  resources :users
  resources :books do
    resources :reviews
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      Make all BOOKs close to your hands
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Manage Library", root_path, id: "logo" %>   
    <nav>

      <ul class="nav navbar-nav">
        <% if logged_in? && current_user.admin %>
          <li><%= link_to "New Book", '/newbook' %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right"> 

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Categories <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu">
               <% Category.all.each do |category| %>
                  <li class= "<%= 'active' if params[:category] == category.types %>">
                    <%= link_to category.types, root_path(category: category.types), class: "link" %>
                  </li>
               <% end %>
            </ul>
          </li>

        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Authors", allauthors_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up",   signup_path %></li>   
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul> 
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="container">
         <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

</html>